# Generated by Django 5.1.7 on 2025-03-31 09:42

import petstagram.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_petphoto_create_at_petphoto_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='get_photos/', validators=[petstagram.photos.models.MaxFileSizeValidator(limit_value=5242880)]),
        ),
    ]
