# Generated by Django 5.1.7 on 2025-04-03 11:15

import WorldOfSpeedApp.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3, message='Username must be at least %(limit_value)d chars long!'), WorldOfSpeedApp.profiles.validators.validate_username])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(help_text='Age requirement: 21 years and above.', validators=[django.core.validators.MinLengthValidator(21)])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
