# Generated by Django 5.1.7 on 2025-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountuser_delete_model1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
